s = "TGCAGAAAAGAGAATACCAAACCGCACTGACGATTTGGTCTCTCTACAAAGTATTACCCCCACACAGTAAATCATTCAGTCAAAGTCATATCAATGGTGTACTGCATAATTAAATTGAACAACTTTCATAAATGCATTGTCTATCCCTTAAACGGTCCCTGAACCCCCCGAAAAAAAGCGTAGATTCCCTTCACTAGTACCAGCACATTCATGGTACGCCATGTGCTATAAGCACGCAGCTGCATTGCATGTGTCAAGGAGAATGTGACCTCTTATCATGCTCGGGAGGTTGTGCAGGTTAGAAAAGACCCCCACTTATAACGGAGTGACCGTGCTTATCTGCGCCCGAAAGTGTAGGCCCAGCCAGCCATCCGGGGCTCAAGTGCGTGGGCTGATATTAGCTTTAACAAGGACTCATACTCGAGAGCACACTGTCAACCCTTCAGTGGCGCTCTTCTGCTACGACTTCTCGCGTTGACAGCCGACTGTGTCTCGGCTCTTACGATGCGTAACCCCAGGCAGACCGGGCCTTTGAGTCACACCACCACGGGTAAAATAATAAAATCCAGAGAGGTCACAATGTGACAGTCGCCCAGGTAAACTGGACTGCGCCCGTTATAAGTATTGGCTTGGGACTATTGCCCACGAACCCAGGGTATCATTTGCTGCGATCACGGCGTTAGCTCAAAAGGATAATCATCAAGCCAAAAATACCACCCCAGCCGGGAGCTAAGATGGTAGAAGTCTAAACGATATGCGAGATGTCAGTGGCAGAGCTTCGTAGAGTTAAAGTAAGCCTCTTATCTGGTATCGTACCCATACTCCCGCAAACCAGTCAGTTCCGACCGAGATGTACCAGACCTATCGACAGCCCCATTT"
a = 0
b = 0
c = 0
d = 0

for i in s:
    if i == "A":
        a = a + 1

    if i == "C":
        b = b + 1

    if i == "G":
        c = c+ 1
    
    if i == "T":
        d = d + 1

print(a, b, c, d)