#!/usr/bin/env python3


s = "TGCAGAAAAGAGAATACCAAACCGCACTGACGATTTGGTCTCTCTACAAAGTATTACCCCCACACAGTAAATCATTCAGTCAAAGTCATATCAATGGTGTACTGCATAATTAAATTGAACAACTTTCATAAATGCATTGTCTATCCCTTAAACGGTCCCTGAACCCCCCGAAAAAAAGCGTAGATTCCCTTCACTAGTACCAGCACATTCATGGTACGCCATGTGCTATAAGCACGCAGCTGCATTGCATGTGTCAAGGAGAATGTGACCTCTTATCATGCTCGGGAGGTTGTGCAGGTTAGAAAAGACCCCCACTTATAACGGAGTGACCGTGCTTATCTGCGCCCGAAAGTGTAGGCCCAGCCAGCCATCCGGGGCTCAAGTGCGTGGGCTGATATTAGCTTTAACAAGGACTCATACTCGAGAGCACACTGTCAACCCTTCAGTGGCGCTCTTCTGCTACGACTTCTCGCGTTGACAGCCGACTGTGTCTCGGCTCTTACGATGCGTAACCCCAGGCAGACCGGGCCTTTGAGTCACACCACCACGGGTAAAATAATAAAATCCAGAGAGGTCACAATGTGACAGTCGCCCAGGTAAACTGGACTGCGCCCGTTATAAGTATTGGCTTGGGACTATTGCCCACGAACCCAGGGTATCATTTGCTGCGATCACGGCGTTAGCTCAAAAGGATAATCATCAAGCCAAAAATACCACCCCAGCCGGGAGCTAAGATGGTAGAAGTCTAAACGATATGCGAGATGTCAGTGGCAGAGCTTCGTAGAGTTAAAGTAAGCCTCTTATCTGGTATCGTACCCATACTCCCGCAAACCAGTCAGTTCCGACCGAGATGTACCAGACCTATCGACAGCCCCATTT"
A = 0
C= 0
G = 0
T = 0

for i in s:
    if i == "A":
        A = A + 1

    if i == "C":
        C = C + 1

    if i == "G":
        G =G + 1
    
    if i == "T":
        T = T + 1

print(A, C, G, T)